name: ESLint and Tests

on: [pull_request]

jobs:
  Analyze Code:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20.16.0'

    - name: Install dependencies
      run: npm install --force

    - name: Run ESLint
      run: npm run eslint

    - name: Run Tests
      run: npm run test:coverage

    - name: Check commit messages
      run: npx commitlint --from=HEAD~1 --to=HEAD